// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Data.Models;

public partial class Asignaciones
{
    public int IdAsignacion { get; set; }

    public int IdProfesor { get; set; }

    public int IdMateria { get; set; }

    public bool Estado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual Materias IdMateriaNavigation { get; set; }

    public virtual Profesores IdProfesorNavigation { get; set; }
}