// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Data.Models;

public partial class Inscripciones
{
    public int IdInscripcion { get; set; }

    public int IdEstudiante { get; set; }

    public int IdMateria { get; set; }

    public bool Estado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual Estudiantes IdEstudianteNavigation { get; set; }

    public virtual Materias IdMateriaNavigation { get; set; }
}