// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Data.Models;

public partial class Materias
{
    public int IdMateria { get; set; }

    public string NombreMateria { get; set; }

    public string CreditoMateria { get; set; }

    public bool Estado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual ICollection<Asignaciones> Asignaciones { get; set; } = new List<Asignaciones>();

    public virtual ICollection<Inscripciones> Inscripciones { get; set; } = new List<Inscripciones>();
}